### ISSUE TITLE
Problem with sum-numbers

### ISSUE THREAD

**Issue by inkpoet63** [CheckiO-Missions/checkio-mission-sum-numbers#8]
Hello,
I was running your mission sum numbers.  When I run the code it is fine, but when I check it, it fails an assertion.  The strange thing is it's not an assertion that's in the code.  Hopefully you can see the screen shot I attached.

![image](https://user-images.githubusercontent.com/69418531/145089002-284cd744-afbd-47be-9b30-cb488414cbde.png)

Thank you,

Bob

**Comment by oduvan** [comment]
Check fails not because of assertion, but because of internal testing system

PS: which browser and OS are you using?
